const { withTenantClient, query } = require('../config/db');
const { recordAudit } = require('../utils/auditLog.util');

async function get(schoolId) {
  return withTenantClient(schoolId, async (client) => {
    const result = await client.query(
      `SELECT * FROM school_payment_configs WHERE school_id = $1`,
      [schoolId]
    );
    return result.rows[0] || null;
  });
}

// Columns the controller may write. callback_token is deliberately NOT here:
// it is generated by the database default and never changes through the API.
const COLUMNS = [
  'mpesa_env', 'mpesa_shortcode_type', 'mpesa_shortcode', 'mpesa_till_number', 'mpesa_account_ref_prefix',
  'consumer_key_enc', 'consumer_key_hint', 'consumer_secret_enc', 'passkey_enc',
  'stk_enabled', 'c2b_enabled', 'c2b_reject_unmatched', 'c2b_registered_at', 'c2b_register_message',
  'b2b_enabled', 'initiator_name', 'initiator_password_enc',
  'last_verified_at', 'last_verify_ok', 'last_verify_message',
];

/**
 * Writes the FULL config row (the controller merges a partial update against
 * the existing row first, so anything not sent is kept). The audit entry says
 * WHICH secrets changed - never their values.
 */
async function upsert(schoolId, cfg, actorUserId, changes = {}) {
  return withTenantClient(schoolId, async (client) => {
    const values = COLUMNS.map((c) => (cfg[c] === undefined ? null : cfg[c]));
    const placeholders = COLUMNS.map((_, i) => `$${i + 3}`);
    const result = await client.query(
      `INSERT INTO school_payment_configs (school_id, updated_by, ${COLUMNS.join(', ')}, updated_at)
       VALUES ($1, $2, ${placeholders.join(', ')}, now())
       ON CONFLICT (school_id) DO UPDATE SET updated_by = EXCLUDED.updated_by, updated_at = now(),
         ${COLUMNS.map((c) => `${c} = EXCLUDED.${c}`).join(', ')}
       RETURNING *`,
      [schoolId, actorUserId || null, ...values]
    );
    await recordAudit(client, {
      schoolId, userId: actorUserId, action: 'update', tableName: 'school_payment_configs', recordId: schoolId,
      details: {
        env: cfg.mpesa_env, shortcodeType: cfg.mpesa_shortcode_type, shortcode: cfg.mpesa_shortcode,
        stkEnabled: cfg.stk_enabled, c2bEnabled: cfg.c2b_enabled, b2bEnabled: cfg.b2b_enabled,
        secretsChanged: changes.secretsChanged || [], secretsRemoved: changes.secretsRemoved || [],
      },
    });
    return result.rows[0];
  });
}

/** Stores the outcome of a "Verify connection" check. */
async function recordVerification(schoolId, { ok, message }) {
  return withTenantClient(schoolId, async (client) => {
    const result = await client.query(
      `UPDATE school_payment_configs
          SET last_verified_at = now(), last_verify_ok = $2, last_verify_message = $3
        WHERE school_id = $1 RETURNING *`,
      [schoolId, !!ok, message ? String(message).slice(0, 300) : null]
    );
    return result.rows[0] || null;
  });
}

/** Stores the outcome of registering the C2B URLs with Safaricom. */
async function recordC2BRegistration(schoolId, { ok, message }, actorUserId) {
  return withTenantClient(schoolId, async (client) => {
    const result = await client.query(
      `UPDATE school_payment_configs
          SET c2b_registered_at = CASE WHEN $2 THEN now() ELSE c2b_registered_at END,
              c2b_register_message = $3
        WHERE school_id = $1 RETURNING *`,
      [schoolId, !!ok, message ? String(message).slice(0, 300) : null]
    );
    await recordAudit(client, {
      schoolId, userId: actorUserId, action: 'register_c2b_urls', tableName: 'school_payment_configs', recordId: schoolId,
      details: { ok: !!ok, message: message ? String(message).slice(0, 200) : null },
    });
    return result.rows[0] || null;
  });
}

/**
 * PUBLIC-callback helper: which school owns this secret URL token?
 * Uses a SECURITY DEFINER database function (see migration 010) so the RLS-protected
 * config table isn't queried without a tenant - it returns nothing but a school id.
 */
async function resolveSchoolIdByToken(token) {
  if (typeof token !== 'string' || !/^[a-f0-9]{64}$/.test(token)) return null;
  const result = await query(`SELECT public.resolve_school_by_payment_token($1) AS school_id`, [token]);
  return result.rows[0] && result.rows[0].school_id ? result.rows[0].school_id : null;
}

module.exports = { get, upsert, recordVerification, recordC2BRegistration, resolveSchoolIdByToken };
